version: '2'

networks:
  palestra-network:
    external: true

services:
  app:
    volumes:
      - ./app:/var/www/html
      - ./.docker/app/nginx/sites-available:/etc/nginx/sites-available
    environment:
      - "WEBROOT=/var/www/html/public"
      - "ENABLE_XDEBUG=1"
    build:
      context: .docker/app
    ports:
      - "8080:80"
    networks:
      - palestra-network

  database:
    image: postgres:10
    environment:
      - "POSTGRES_DB=palestra"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "43542:5432"
    networks:
      - palestra-network