version: '2'

networks:
  grammatista-network:
    external: true

services:
  app:
    volumes:
      - ./app:/var/www/html
      - ./.docker/app/nginx/sites-available:/etc/nginx/sites-available
    environment:
      - "WEBROOT=/var/www/html/public"
      - "ENABLE_XDEBUG=1"
    build:
      context: .docker/app
    ports:
      - "8080:80"
    networks:
      - grammatista-network

  database:
    image: postgres:10
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=grammatista"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=very-very-very-strong-postgres-password"
    ports:
      - "43542:5432"
    networks:
      - grammatista-network

  redis:
    image: redis:4.0.2
    command: redis-server --requirepass very-very-very-strong-redis-password
    ports:
      - "6379:6379"
    networks:
      - grammatista-network